export const FETCH_COURSE_LIST = 'FETCH_COURSE_LIST';
export const FETCH_COURSE_DETAIL = 'FETCH_COURSE_DETAIL';
export const FETCH_OPEN_INFO = 'FETCH_OPEN_INFO';
export const FETCH_LESSON_ENROLL = 'FETCH_LESSON_ENROLL';
export const FETCH_ORDER_CONFIRM = 'FETCH_ORDER_CONFIRM';
export const UPDATE_COURSE_SCROLL = 'UPDATE_COURSE_SCROLL';
